<?php

$potentialTextMemesNoEmoji = array(
  "This offends me as a vegan bitcoin trading hipster Native-American-Indo-Chinese hybrid alien agnostic-atheist German engineer who vapes fairtrade organic decaffeinated compressed and hydrated extra-protein soy breast milk on the regular and does Hindi Kama Sutra naked crossfit yoga 5 times per week. I'm also a neoliberal male feminist and identify myself as a pastafarian pansexual leftist Apache helicopter dog of mega multi alpha beta gamma delta omega combo god of hyper death who's in a polygamous polyamorous relationship to the chihuahua which helped me cross the border of Mexico because it hates Donald Trump. My dog also walks me to the park and doggy styles me, if you find that weird you're an ignorant arrogant homophobic gender-assuming globaphobic bloodthirsty gun-loving bestial sexist racist incestuous white-previlege misogynistic biased objectified raped privileged Nazi slave owner terrorist",

  "What the jiminy crickets did you just flaming say about me, you little bozo? I’ll have you know I graduated top of my class in the Cub Scouts, and I’ve been involved in numerous secret camping trips in Wyoming, and I have over 300 confirmed knots. I am trained in first aid and I’m the top bandager in the entire US Boy Scouts (of America). You are nothing to me but just another friendly face. I will clean your wounds for you with precision the likes of which has never been seen before on this annual trip, mark my words. You think you can get away with saying those shenanigans to me over the Internet? Think again, finkle. As we speak I am contacting my secret network of MSN friends across the USA and your IP is being traced right now so you better prepare for the seminars, man. The storm that wipes out the pathetic little thing you call your bake sale. You’re frigging done, kid. I can be anywhere, anytime, and I can tie knots in over seven hundred ways, and that’s just with my bare hands. Not only am I extensively trained in road safety, but I have access to the entire manual of the United States Boy Scouts (of America) and I will use it to its full extent to train your miserable butt on the facts of the continents, you little schmuck. If only you could have known what unholy retribution your little 'clever' comment was about to bring down upon you, maybe you would have held your silly tongue. But you couldn’t, you didn’t, and now you’re paying the price, you goshdarned sillyhead. I will throw leaves all over you and you will dance in them. You’re friggin done, kiddo."
  ,

  "The FitnessGram™ Pacer Test is a multistage aerobic capacity test that progressively gets more difficult as it continues. The 20 meter pacer test will begin in 30 seconds. Line up at the start.",


"What the darn-diddily-doodily did you just say about me, you little witcharooney? I’ll have you know I graduated top of my class at Springfield Bible College, and I’ve been involved in numerous secret mission trips in Capital City, and I have over 300 confirmed baptisms. I am trained in the Old Testament and I’m the top converter in the entire church mission group. You are nothing to me but just another heathen. I will cast your sins out with precision the likes of which has never been seen before in Heaven, mark my diddily-iddilly words. You think you can get away with saying that blasphemy to me over the Internet? Think again, friendarino. As we speak I am contacting my secret network of evangelists across Springfield and your IP is being traced by God right now so you better prepare for the storm, maggorino. The storm that wipes out the diddily little thing you call your life of sin. You’re going to Church, kiddily-widdily. Jesus can be anywhere, anytime, and he can turn you to the Gospel in over infinity ways, and that’s just with his bare hands. Not only am I extensively trained in preaching to nonbelievers, but I have access to the entire dang- diddily Bible collection of the Springfield Bible College and I will use it to its full extent to wipe your sins away off the face of the continent, you diddily-doo satan-worshipper. If only you could have known what holy retribution your little “clever” comment was about to bring down upon you from the Heavens, maybe you would have held your darn-diddily-fundgearoo tongue. But you couldn’t, you didn’t, and now you’re clean of all your sins, you widdillo-skiddily neighborino. I will sing hymns of praise all over you and you will drown in the love of Christ. You’re farn-foodily- flank-fiddily reborn, kiddo-diddily."
,

"This is so sad 😞 Alexa, play Despacito 2

ɴᴏᴡ ᴘʟᴀʏɪɴɢ:

Despacito 2 (Feat: Lil Pump, XXX Tentacion, MinecraftAwesomeParodies, Pink Guy, Death Grips, 6ix9ine, 2pac, Joji, Lil Peep, Lil Yatchy, Ameer Vann, Twenty One Pilots, Blank Banshee, Lil Xan, Kuwait Grips, Tyler The Creator, Jaden Smith, Morrinsoney, Kurt Cobain, Yung Caucasian, DJ Pajamas, Link Wrey, Ice T, Péricles, Lil Gay, Rihanna, Chris Brown, Beyoncé, Eazy E, Pink Floyd, Cal Chuchesta, Ice Cube, BROCKHAMPTON, Odd Future, David Bowie, Elon Musk, Politikz, Yung Thug, Foo Fighters, Billie Holiday, Nat King Cole, My Chemical Romance, Smash Mouth, DJ Khaled, Imagine Dragons, Bjork, The Notourious B.I.G, Mad Dogg, Garth Brooks, JPEG Mafia, Mozart, Car Seat Headrest, Sex Bob-Omb, Frank Jav Cee, Sandtimer, Skrillex, Ghostemane, Nikki Minaj, Kid Cudi, Metallica, John Lennon and The Plastic Yoko Band, Pogo, AC DC, 2 8 1 4, The Beatles, Rolling Stones, Swans, Alexander Hamilton, Jack Douglass, Talking Heads, Arctic Monkeys, Paramore, Iron Maiden, Panic! At The Disco, Nirvana, Avril Lavigne, All Time Low, AJR, Green Day, Deadmau5, Simple Plan, Vanilla Ice, Eminem, The Killers, Drake, Hannah Montana, Vacations, Frank Ocean, Radiohead, Marshmello, Rex Orange County, The Strokes, Kali Uchis, Cardi B, Fall Out Boy, Blink-182, Michael Jackson, Agepê, Jack Johnson, Ninja Sex Party, BTS, Floral Shoppe, Pusha T, Eric Clapton, Pitbull, Will.i.am, Black Eyed Peas, Beastie Boys, Petshop Boys, R.E.M, Tame Impala, Backstreet Boys, The Ink Spots, Kanye West, Dean Martin, Logic, Marty Robbins, KESHA, G-Eazy, Weezer, Toto, Darude, Shawn Mendes, Maroon Five, Father John Misty, Ed Sheeran, Post Malone, American Hi-Fi, Dashboard Confession, Miley Cyrus, Bob Marley, Nardwuar, King Buzzo, Marvin Gaye, Childish Gambino, Wu Tang Clan, Yellowcard, Leon Noel, Simon and Garfunkel, Elvis Presley, Justin Bieber, Matty B, Dawn, Dawn, Dawn, Johnny Cash, Helen Forrest, Hank Thompson, Tina Fonda, Prince, Rick James, Frank Sinatra, Lil Uzi Vert, ASAP Mob, Home, The Smiths, Joy Division, Luis Fonsi, Daddy Yankee)
"
,
"Excuse me, but I have played many a hentai game so I am no stranger to a naked female or how to pleasure one. The idea that a gamer of my intellect would not know how to deal with a mere female human without clothing is simply laughable. I have been though hundreds, nay, thousands of simulations which cover every permutation of events that could possibly happen with a female so I would absolutely know how to provide her pleasure given the opportunity. Don't underestimate the power of hentai, my friend",

"So today in Spanish class, my teacher told us that we would be listening to a song in Spanish. Already, I began to tremble. I had a bad feeling about this. “Which one?” I ask shakily, not wanting to hear the answer. “Despacito” She responds. I begin to hyperventilate. My worst fears have been realized. I fade in and out of conciseness. I clamp my palms over my ears, but I know it’s futile. The song plays. I’m crying now, praying. God, Allah, Buddha please help me. I curl up on the floor. There’s nothing I can do now. And then it happens. The chorus plays. The girls in my class open their mouths. The screams of the damned, the shrieks of the tortured fill my ears and bounce around my skull. My eardrums rupture, blood leaking out. I try to scream, but no sound comes out. I can only sit there, violently shaking as it happens to me. After what seems like hours, it’s finally over. I try to move, but I cannot make myself. My brain shuts down as my vision fades to black. I muster the last of my energy, uttering the accursed word. Despacito"
,
"As I sat in the Harvard Dean's office in front of the board of reviewers for my application, the Dean asks me 'Why should you be a good candidate for this school?' They seemed bored but I replied 'Well I was born a child prodigy, placed 1st in my state spelling bee for three consecutive years, I can speak eight different languages not counting Latin, play four different instruments, I skipped grades 4 through 6, and graduated my high school as valedictorian at the age of 14. I then worked as an intern at both Telsa, and NASA.' Suddenly the room burst into laughter and many of board instantly started scribbling down 'No' near the application check marks. The Dean says 'Sorry but you are just not the type we are looking for.' But then I said 'Excuse me but I wasn't finished... I watch Rick and Morty' The Dean looked at me like an idiot and said 'So....?' Then I replied with a smile 'And I understand all the references and subtle jokes' An audible gasp let out by the board was so loud the secretary had to come in. You could hear a pin drop and then suddenly all at once the entire board clicked their pens on the 'Approved Box' and I was instantly handed a diploma and now I'm teaching advanced physicals there. I guess you can say I'm pretty smart."  ,

"Technically, pansexuality is the least gay sexuality

If you are straight, you like girls, who like guys, which means it's 25% gay

If you are gay, well that's 100% gay

Bisexuality is 50% gay, because you like both

Pansexuality however, is an attraction to all the genders, 56 are politically recognized, and only one is male, so Pansexuality only makes you 1.78% gay

This concludes my research, good day!"

);

function generateCopyPasta(){
  global $potentialTextMemesNoEmoji;
  // $emoji_list = array('😁','😂','😃','😄','😅','😆','😉','😊','😋','😌','😍','😏','😒','😓','😔','😖','😘','😚','😜','😝','😞','😠','😡','😢','😣','😤','😥','😨','😩','😪','😫','😭','😰','😱','😲','😳','😵','😷','😸','😹','😺','😻','😼','😽','😾','😿','🙀','🙅','🙆','🙇','🙈','🙉','🙊','🙋','🙌','🙍','🙎','🙏','🚀','🚃','🚄','🚅','🚇','🚉','🚌','🚏','🚑','🚒','🚓','🚕','🚗','🚙','🚚','🚢','🚤','🚥','🚧','🚨','🚩','🚪','🚫','🚬','🚭','🚲','🚶','🚹','🚺','🚻','🚼','🚽','🚾','🛀','🅰','🅱','🅾','🅿','🆎','🆑','🆒','🆓','🆔','🆕','🆖','🆗','🆘','🆙','🆚','🈁','🈂','🈚','🈯','🈲','🈳','🈴','🈵','🈶','🈷','🈸','🈹','🈺','🉐','🉑','🀄','🃏','🌀','🌁','🌂','🌃','🌄','🌅','🌆','🌇','🌈','🌉','🌊','🌋','🌌','🌏','🌑','🌓','🌔','🌕','🌙','🌛','🌟','🌠','🌰','🌱','🌴','🌵','🌷','🌸','🌹','🌺','🌻','🌼','🌽','🌾','🌿','🍀','🍁','🍂','🍃','🍄','🍅','🍆','🍇','🍈','🍉','🍊','🍌','🍍','🍎','🍏','🍑','🍒','🍓','🍔','🍕','🍖','🍗','🍘','🍙','🍚','🍛','🍜','🍝','🍞','🍟','🍠','🍡','🍢','🍣','🍤','🍥','🍦','🍧','🍨','🍩','🍪','🍫','🍬','🍭','🍮','🍯','🍰','🍱','🍲','🍳','🍴','🍵','🍶','🍷','🍸','🍹','🍺','🍻','🎀','🎁','🎂','🎃','🎄','🎅','🎆','🎇','🎈','🎉','🎊','🎋','🎌','🎍','🎎','🎏','🎐','🎑','🎒','🎓','🎠','🎡','🎢','🎣','🎤','🎥','🎦','🎧','🎨','🎩','🎪','🎫','🎬','🎭','🎮','🎯','🎰','🎱','🎲','🎳','🎴','🎵','🎶','🎷','🎸','🎹','🎺','🎻','🎼','🎽','🎾','🎿','🏀','🏁','🏂','🏃','🏄','🏆','🏈','🏊','🏠','🏡','🏢','🏣','🏥','🏦','🏧','🏨','🏩','🏪','🏫','🏬','🏭','🏮','🏯','🏰','🐌','🐍','🐎','🐑','🐒','🐔','🐗','🐘','🐙','🐚','🐛','🐜','🐝','🐞','🐟','🐠','🐡','🐢','🐣','🐤','🐥','🐦','🐧','🐨','🐩','🐫','🐬','🐭','🐮','🐯','🐰','🐱','🐲','🐳','🐴','🐵','🐶','🐷','🐸','🐹','🐺','🐻','🐼','🐽','🐾','👀','👂','👃','👄','👅','👆','👇','👈','👉','👊','👋','👌','👍','👎','👏','👐','👑','👒','👓','👔','👕','👖','👗','👘','👙','👚','👛','👜','👝','👞','👟','👠','👡','👢','👣','👤','👦','👧','👨','👩','👪','👫','👮','👯','👰','👱','👲','👳','👴','👵','👶','👷','👸','👹','👺','👻','👼','👽','👾','👿','💀','💁','💂','💃','💄','💅','💆','💇','💈','💉','💊','💋','💌','💍','💎','💏','💐','💑','💒','💓','💔','💕','💖','💗','💘','💙','💚','💛','💜','💝','💞','💟','💠','💡','💢','💣','💤','💥','💦','💧','💨','💩','💪','💫','💬','💮','💯','💰','💱','💲','💳','💴','💵','💸','💹','💺','💻','💼','💽','💾','💿','📀','📁','📂','📃','📄','📅','📆','📇','📈','📉','📊','📋','📌','📍','📎','📏','📐','📑','📒','📓','📔','📕','📖','📗','📘','📙','📚','📛','📜','📝','📞','📟','📠','📡','📢','📣','📤','📥','📦','📧','📨','📩','📪','📫','📮','📰','📱','📲','📳','📴','📶','📷','📹','📺','📻','📼','🔃','🔊','🔋','🔌','🔍','🔎','🔏','🔐','🔑','🔒','🔓','🔔','🔖','🔗','🔘','🔙','🔚','🔛','🔜','🔝','🔞','🔟','🔠','🔡','🔢','🔣','🔤','🔥','🔦','🔧','🔨','🔩','🔪','🔫','🔮','🔯','🔰','🔱','🔲','🔳','🔴','🔵','🔶','🔷','🔸','🔹','🔺','🔻','🔼','🔽','🕐','🕑','🕒','🕓','🕔','🕕','🕖','🕗','🕘','🕙','🕚','🕛','🗻','🗼','🗽','🗾','🗿','😀','😇','😈','😎','😐','😑','😕','😗','😙','😛','😟','😦','😧','😬','😮','😯','😴','😶','🚁','🚂','🚆','🚈','🚊','🚍','🚎','🚐','🚔','🚖','🚘','🚛','🚜','🚝','🚞','🚟','🚠','🚡','🚣','🚦','🚮','🚯','🚰','🚱','🚳','🚴','🚵','🚷','🚸','🚿','🛁','🛂','🛃','🛄','🛅','🌍','🌎','🌐','🌒','🌖','🌗','🌘','🌚','🌜','🌝','🌞','🌲','🌳','🍋','🍐','🍼','🏇','🏉','🏤','🐀','🐁','🐂','🐃','🐄','🐅','🐆','🐇','🐈','🐉','🐊','🐋','🐏','🐐','🐓','🐕','🐖','🐪','👥','👬','👭','💭','💶','💷','📬','📭','📯','📵','🔀','🔁','🔂','🔄','🔅','🔆','🔇','🔉','🔕','🔬','🔭','🕜','🕝','🕞','🕟','🕠','🕡','🕢','🕣','🕤','🕥','🕦','🕧');
  $emoji_list = array('😂', '🖕', '💦🍌', '💦','💩', '👉👌', '😖', '😣', '😩', '😫💦💦🙏🏿', '✊🏽✊🏽💦');

   $randomEmoji = $emoji_list[array_rand($emoji_list)];
   $randomCopypasta = $potentialTextMemesNoEmoji[array_rand($potentialTextMemesNoEmoji)];
  // return implode($randomEmoji, str_split($randomCopypasta));
  return str_replace(' ', $randomEmoji, $randomCopypasta);

}

print(generateCopyPasta());
